return {}
-- return {
--     {
--         "williamboman/mason.nvim",
--         config = function()
--             require("mason").setup()
--         end
--     },
--     {
--         "williamboman/mason-lspconfig.nvim",
--         config = function ()
--             require("mason-lspconfig").setup({
--                 ensure_installed = {"lua_ls", "gopls", "tsserver", "tailwindcss", "templ", "dockerls", "docker_compose_language_service"}
--             })
--         end
--     },
--     {
--         "neovim/nvim-lspconfig",
--         config = function ()
--             local lspconfig = require("lspconfig")
--
--             lspconfig.lua_ls.setup({})
--             lspconfig.gopls.setup({})
--             lspconfig.tsserver.setup({})
--             lspconfig.tailwindcss.setup({})
--             lspconfig.templ.setup({})
--             lspconfig.dockerls.setup({})
--             lspconfig.docker_compose_language_service.setup({})
--
--             -- Keymaps
--             local opts = { noremap = true, silent = true }
--             local keymap = vim.keymap
--
--             opts.desc = "Show documentation of what is under the cursor"
--             vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
--
--             opts.desc = "Go to definition"
--             vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
--
--             opts.desc = "Show code actions"
--             keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, opts)
--         end
--     }
-- }
